version: "3.9"
services:
  # Runs a Prysm beacon chain from a specified genesis state created in the previous step
  # and connects to go-ethereum in the same network as the execution client.
  # The account used in go-ethereum is set as the suggested fee recipient for transactions
  # proposed via the validators attached to the beacon node.
  beacon-chain:
    build: l1-beacon-chain
    container_name: beacon-chain
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
      - 6060:6060
      - 9090:9090
    depends_on:
      geth:
        condition: service_started

  # Runs the go-ethereum execution client with the specified, unlocked account and necessary
  # APIs to allow for proof-of-stake consensus via Prysm.
  geth:
    build: l1-geth
    container_name: l1_node
    ports:
      - "8551"
      - "8545"
      - "8546"

  # We run a validator client with 64, deterministically-generated keys that match
  # The validator keys present in the beacon chain genesis state generated a few steps above.
  validator:
    build: l1-validator
    container_name: validator
    depends_on:
      beacon-chain:
        condition: service_started

  l2_execution_engine:
    container_name: l2_node
    image: gcr.dockerproxy.com/evmchain/taiko-geth:taiko
    restart: unless-stopped
    pull_policy: always
    volumes:
      - .:/host
    ports:
      - "8545"
      - "8546"
      - "8551"
    command:
      - --nodiscover
      - --gcmode
      - archive
      - --syncmode
      - full
      - --datadir
      - /data/taiko-geth
      - --networkid
      - "167001"
      - --metrics
      - --metrics.expensive
      - --metrics.addr
      - "0.0.0.0"
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.vhosts
      - "*"
      - --http.corsdomain
      - "*"
      - --ws
      - --ws.addr
      - "0.0.0.0"
      - --ws.origins
      - "*"
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.port
      - "8551"
      - --authrpc.vhosts
      - "*"
      - --authrpc.jwtsecret
      - /host/jwt.hex
      - --allow-insecure-unlock
      - --http.api
      - admin,debug,eth,net,web3,txpool,miner,taiko
      - --ws.api
      - admin,debug,eth,net,web3,txpool,miner,taiko
      - --taiko